eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:      defaultZone: ${EUREKA_URI:https://localhost:8761/eureka}
  instance:
    hostname: localhost
    non-secure-port-enabled: false
    prefer-ip-address: false
    secure-port: ${server.port}
    secure-port-enabled: true

logging:
  level:
    org.springframework.web: DEBUG

ribbon:
  eureka:
    enabled: true

server:
  port: 8770
  ssl:
    key-alias: localhost
    key-store: classpath:keystore-rsa.jks
    key-store-password: localhost
    key-store-type: JKS

spring:
  application:
    name: app-api
  profiles:
    active: dev

jwt:
  key: FB8D6591183B4AEA3E6975BBDFBD52FB99DD2E4BF565B634A1168C488E