eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: localhost
    # non-secure-port-enabled: false
    prefer-ip-address: false
    # secure-port: ${server.port}
    # secure-port-enabled: true

ribbon:
  eureka:
    enabled: true

server:
  port: 8760
  shutdown: graceful
  # ssl:
  #   key-alias: localhost
  #   key-store: classpath:keystore-rsa.jks
  #   key-store-password: localhost
  #   key-store-type: JKS

spring:
  application:
    name: app-gateway
  profiles:
    active: dev

zuul:
  ssl-hostname-validation-enabled: false
  routes:
    api:
      path: /app/api/**
      service-id: APP-API
      strip-prefix: true
      sensitive-headers:
